# Generated by Django 4.1.2 on 2022-10-20 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_carro', models.CharField(max_length=200, verbose_name='Carro')),
                ('cor', models.CharField(choices=[('yellow', 'yellow'), ('blue', 'blue'), ('gray', 'gray')], max_length=200)),
                ('modelos', models.CharField(choices=[('hatch', 'hatch'), ('sedan', 'sedan'), ('convertible', 'convertible')], max_length=200)),
                ('proprietarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietarios', related_query_name='proprietarios', to='proprietarios.proprietarios', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['nome_do_carro'],
            },
        ),
    ]
