# Generated by Django 4.1.2 on 2022-10-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Proprietario',
                'verbose_name_plural': 'Proprietarios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(choices=[('yellow', 'yellow'), ('blue', 'blue'), ('gray', 'gray')], max_length=200)),
                ('modelos', models.CharField(choices=[('hatch', 'hatch'), ('sedan', 'sedan'), ('convertible', 'convertible')], max_length=200)),
                ('proprietarios', models.ForeignKey(limit_choices_to=3, on_delete=django.db.models.deletion.CASCADE, to='list.proprietarios')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['cor'],
            },
        ),
    ]
