# Generated by Django 4.1.2 on 2022-10-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_carros_proprietarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carros',
            options={'ordering': ['nome_do_carro'], 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AddField(
            model_name='carros',
            name='nome_do_carro',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carros',
            name='proprietarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.proprietarios'),
        ),
    ]
