# Generated by Django 4.1.2 on 2022-10-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_carros_options_carros_nome_do_carro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietarios',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
