# Generated by Django 4.1.2 on 2022-10-19 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_proprietarios_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietarios',
            name='possivel_venda',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carros',
            name='nome_do_carro',
            field=models.CharField(max_length=200, unique=True, verbose_name='Carro'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='proprietarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietarios', related_query_name='proprietarios', to='list.proprietarios', verbose_name='Proprietário'),
        ),
    ]
