# Generated by Django 4.1.2 on 2022-10-19 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_alter_carros_proprietarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='proprietarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='list.proprietarios', verbose_name='Proprietário'),
            preserve_default=False,
        ),
    ]
