# Generated by Django 4.1.2 on 2022-10-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_alter_carros_proprietarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietarios',
            name='possivel_venda',
            field=models.BooleanField(default=True),
        ),
    ]
