# Generated by Django 4.1.2 on 2022-10-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietarios',
            name='possivel_venda',
            field=models.BooleanField(default=True),
        ),
    ]
